# ================================
# application.yml (Main Configuration)
# Place this in: src/main/resources/application.yml
# ================================

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user-service
  config:
    import: optional:file:.env[.properties]

  # Default Database Configuration
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      leak-detection-threshold: 60000
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  # Jackson JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    default-property-inclusion: non_null

# JWT Configuration from Environment
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true

# Application Information
info:
  app:
    name: EventSphere User Service
    description: User management and authentication service
    version: 1.0.0

# Logging Configuration
logging:
  level:
    com.eventsphere.user: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    '[org.apache.coyote.http11.Http11InputBuffer]': ERROR  # Suppress invalid HTTP request errors
    '[org.apache.tomcat.util.http.parser.HttpParser]': ERROR  # Suppress HTTP parsing errors
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"